# Generated by Django 3.1.6 on 2021-03-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contet',
            new_name='content',
        ),
    ]
