# Generated by Django 3.1.6 on 2021-03-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_blog', '0002_auto_20210318_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tittle',
            new_name='title',
        ),
    ]
